name: Deploy to GitHub Pages

on:
  # 當推送到 main 分支時觸發
  push:
    branches: [ main ]
  # 當建立 PR 到 main 分支時觸發（僅建構，不部署）
  pull_request:
    branches: [ main ]
  # 允許手動觸發
  workflow_dispatch:

# 設定 GITHUB_TOKEN 權限
permissions:
  contents: read
  pages: write
  id-token: write

# 確保同時只有一個部署在進行
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 建構和測試
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.1
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Generate Astro types
        run: pnpm astro sync
        
      - name: Run type checking
        run: pnpm run typecheck
        
      - name: Run linting
        run: pnpm run lint
        
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        
      - name: Build with Astro
        run: |
          pnpm run build \
            --site "${{ steps.pages.outputs.origin }}" \
            --base "${{ steps.pages.outputs.base_path }}"
            
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # 部署到 GitHub Pages（僅在 main 分支）
  deploy:
    needs: build
    runs-on: ubuntu-latest
    # 僅在 main 分支且非 PR 時部署
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4